# Generated by Django 4.1.2 on 2022-10-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velogest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='owers',
            new_name='owners',
        ),
    ]
