# Generated by Django 4.1.2 on 2022-10-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velogest', '0003_campaign_created_at_campaign_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedByLatitudeType1Sensor',
            fields=[
            ],
            options={
                'ordering': ['latitude'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('velogest.sensor',),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField()),
                ('record_number', models.IntegerField()),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor', to='velogest.sensor')),
            ],
        ),
    ]
