# Generated by Django 4.1.2 on 2022-10-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velogest', '0004_alter_sensor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('T1', 'type 1'), ('T2', 'type 2')], default='T1', max_length=20),
        ),
    ]
